"""BayesFilter core contracts and reference backends."""

from __future__ import annotations

from importlib import import_module

__all__ = [
    "CompiledValuePathClassification",
    "CompiledValuePathMode",
    "FactorBackendAuditResult",
    "BackendParityGate",
    "BackendParityResult",
    "BackendParityRow",
    "CovariancePositiveDefiniteError",
    "FilterDerivativeResult",
    "FilterRunMetadata",
    "FilterValueResult",
    "FullChainHMCConfig",
    "FullChainHMCRunResult",
    "CandidateResult",
    "EVIDENCE_MANIFEST_SCOPES",
    "EvidenceManifest",
    "GPUSelection",
    "HMCFailureClassification",
    "HMC_TUNING_POLICY_LABELS",
    "HMCDiagnosticSummary",
    "HMCLogAcceptSummary",
    "HMCScreenResult",
    "HMCTuningDiagnosticResult",
    "HMCTuningPolicy",
    "HessianPosteriorAdapter",
    "FactorizationFailure",
    "FixedTrajectoryCandidateResult",
    "FixedTrajectoryTuningConfig",
    "FixedTrajectoryTuningResult",
    "InvalidCompiledValuePathContract",
    "InvalidNonlinearSSMContract",
    "LinearGaussianStateSpace",
    "LinearGaussianStateSpaceDerivatives",
    "LatentAffineHMCTransform",
    "MassMatrixResult",
    "NonlinearFilterValuePathContract",
    "NonlinearFilterValueStaticShape",
    "NonlinearSSMAdapterContract",
    "NonlinearSSMStaticShape",
    "ObservationSemantics",
    "ParameterTransformMetadata",
    "PosteriorAdapter",
    "PrecomputedMassArtifact",
    "PrecomputedMAP",
    "PartialResultSnapshot",
    "PriorSupportError",
    "ReducerRowStatus",
    "RegularizationConvention",
    "RunManifest",
    "SpectralDerivativeCertificationResult",
    "StatePartition",
    "StageEvent",
    "TIMING_BUCKET_NAMES",
    "TFFilterDerivativeResult",
    "TFFilterDiagnostics",
    "TFFilterValueResult",
    "TFLinearGaussianStateSpace",
    "TFLinearGaussianStateSpaceDerivatives",
    "TFLinearValueBackend",
    "TFQRLinearDerivativeBackend",
    "TFQRLinearValueBackend",
    "TFSVDLinearValueBackend",
    "TFRegularizationDiagnostics",
    "TFSigmaPointDiagnostics",
    "TFSigmaPointRule",
    "TFSigmaPointValueBackend",
    "TFStructuralFirstDerivatives",
    "TFStructuralStateSpace",
    "TFSmoothEighFactorFirstDerivatives",
    "TimingBucket",
    "TimeoutRecord",
    "UnsupportedValueScoreAuthority",
    "ValueScoreCapability",
    "ValueScorePosteriorAdapter",
    "WelfordCovarianceResult",
    "WindowedMassAdaptationConfig",
    "WindowedMassAdaptationResult",
    "WindowedMassUpdate",
    "WindowedWarmupWindow",
    "VALID_REDUCER_STATUSES",
    "WorkerManifest",
    "WorkerRecord",
    "StructuralFilterConfig",
    "SolveResidualError",
    "StationarityError",
    "TargetFailureClassification",
    "TargetFailurePolicy",
    "TargetPolicyEvaluation",
    "TargetRegionError",
    "affine_structural_to_linear_gaussian_tf",
    "append_heartbeat",
    "assert_cpu_only_env",
    "append_stage_event",
    "audit_factor_backend",
    "build_trusted_gpu_snapshot",
    "build_worker_manifest",
    "canonical_candidate_order",
    "build_windowed_warmup_schedule",
    "certify_spectral_derivative_region",
    "classify_target_failure_mode",
    "configs_match_exact",
    "classify_fixed_kernel_screen_with_tuning_policy",
    "classify_hmc_screen",
    "classify_hmc_tuning_diagnostic",
    "covariance_from_negative_hessian",
    "covariance_from_precision",
    "ensure_cpu_only_env",
    "evaluate_target_with_failure_policy",
    "find_forbidden_compiled_value_tokens",
    "latent_to_position",
    "latent_value_and_score",
    "make_affine_structural_tf",
    "make_timing_bucket",
    "pointwise_deterministic_residuals",
    "production_leapfrog_count",
    "record_timeout",
    "record_worker_result",
    "regularize_covariance",
    "reduce_worker_artifacts",
    "normalize_hmc_tuning_policy",
    "require_executable_tuning_policy",
    "run_fixed_trajectory_tuning_diagnostic",
    "run_gaussian_dual_averaging_diagnostic",
    "run_windowed_mass_adaptation_diagnostic",
    "run_full_chain_tfp_hmc",
    "select_first_tie_candidate",
    "select_preferred_gpu",
    "screen_hmc_diagnostics",
    "solve_kalman_score_hessian",
    "stable_adapter_signature",
    "stale_artifacts_match_exact",
    "stable_config_hash",
    "stale_match_payload",
    "stable_nonlinear_filter_value_path_signature",
    "stable_nonlinear_ssm_program_signature",
    "static_unroll_chain_value_and_score",
    "structural_block_metadata",
    "structural_filter_diagnostics",
    "structural_filter_metadata",
    "summarize_hmc_diagnostics",
    "summarize_log_accept_ratios",
    "tf_cut4g_sigma_point_rule",
    "tf_kalman_filter",
    "tf_kalman_log_likelihood",
    "tf_linear_gaussian_log_likelihood",
    "tf_masked_kalman_filter",
    "tf_masked_kalman_log_likelihood",
    "tf_qr_linear_gaussian_log_likelihood",
    "tf_qr_linear_gaussian_score",
    "tf_qr_linear_gaussian_score_hessian",
    "tf_qr_sqrt_kalman_filter",
    "tf_qr_sqrt_kalman_log_likelihood",
    "tf_qr_sqrt_kalman_score_hessian",
    "tf_qr_sqrt_masked_kalman_filter",
    "tf_qr_sqrt_masked_kalman_log_likelihood",
    "tf_qr_sqrt_masked_kalman_score_hessian",
    "tf_svd_cubature_score",
    "tf_svd_cut4_filter",
    "tf_svd_cut4_log_likelihood",
    "tf_svd_cut4_score",
    "tf_svd_kalman_log_likelihood",
    "tf_svd_linear_gaussian_log_likelihood",
    "tf_svd_linear_gaussian_score_hessian",
    "tf_svd_masked_kalman_log_likelihood",
    "tf_svd_sigma_point_filter",
    "tf_svd_sigma_point_log_likelihood",
    "tf_svd_sigma_point_log_likelihood_with_rule",
    "tf_svd_sigma_point_placement",
    "tf_svd_sigma_point_score_with_rule",
    "tf_svd_ukf_score",
    "tensorflow_nonlinear_value_path_contract",
    "tf_unit_sigma_point_rule",
    "validate_precomputed_map",
    "validate_windowed_shrinkage_target",
    "validate_filter_config",
    "validate_nonlinear_ssm_contract",
    "value_score_capability",
    "welford_covariance",
    "whitening_from_covariance",
    "write_partial_result_snapshot",
    "write_evidence_manifest",
    "write_worker_manifest",
]

_EXPORT_MODULES = {
    "CompiledValuePathClassification": "bayesfilter.nonlinear",
    "CompiledValuePathMode": "bayesfilter.nonlinear",
    "FactorBackendAuditResult": "bayesfilter.backends",
    "BackendParityGate": "bayesfilter.inference",
    "BackendParityResult": "bayesfilter.inference",
    "BackendParityRow": "bayesfilter.inference",
    "CovariancePositiveDefiniteError": "bayesfilter.inference",
    "SpectralDerivativeCertificationResult": "bayesfilter.backends",
    "audit_factor_backend": "bayesfilter.backends",
    "certify_spectral_derivative_region": "bayesfilter.backends",
    "FilterDerivativeResult": "bayesfilter.results",
    "FilterRunMetadata": "bayesfilter.structural",
    "FilterValueResult": "bayesfilter.results",
    "FullChainHMCConfig": "bayesfilter.inference",
    "FullChainHMCRunResult": "bayesfilter.inference",
    "CandidateResult": "bayesfilter.runtime",
    "EVIDENCE_MANIFEST_SCOPES": "bayesfilter.runtime",
    "EvidenceManifest": "bayesfilter.runtime",
    "GPUSelection": "bayesfilter.runtime",
    "HMCFailureClassification": "bayesfilter.inference",
    "HMC_TUNING_POLICY_LABELS": "bayesfilter.inference",
    "HMCDiagnosticSummary": "bayesfilter.inference",
    "HMCLogAcceptSummary": "bayesfilter.inference",
    "HMCScreenResult": "bayesfilter.inference",
    "HMCTuningDiagnosticResult": "bayesfilter.inference",
    "HMCTuningPolicy": "bayesfilter.inference",
    "HessianPosteriorAdapter": "bayesfilter.inference",
    "FactorizationFailure": "bayesfilter.inference",
    "FixedTrajectoryCandidateResult": "bayesfilter.inference",
    "FixedTrajectoryTuningConfig": "bayesfilter.inference",
    "FixedTrajectoryTuningResult": "bayesfilter.inference",
    "InvalidCompiledValuePathContract": "bayesfilter.nonlinear",
    "InvalidNonlinearSSMContract": "bayesfilter.inference",
    "LinearGaussianStateSpace": "bayesfilter.linear.types",
    "LinearGaussianStateSpaceDerivatives": "bayesfilter.linear.types",
    "LatentAffineHMCTransform": "bayesfilter.inference",
    "MassMatrixResult": "bayesfilter.inference",
    "NonlinearFilterValuePathContract": "bayesfilter.nonlinear",
    "NonlinearFilterValueStaticShape": "bayesfilter.nonlinear",
    "NonlinearSSMAdapterContract": "bayesfilter.inference",
    "NonlinearSSMStaticShape": "bayesfilter.inference",
    "ObservationSemantics": "bayesfilter.inference",
    "ParameterTransformMetadata": "bayesfilter.inference",
    "PosteriorAdapter": "bayesfilter.inference",
    "PrecomputedMassArtifact": "bayesfilter.inference",
    "PrecomputedMAP": "bayesfilter.inference",
    "PriorSupportError": "bayesfilter.inference",
    "PartialResultSnapshot": "bayesfilter.runtime",
    "ReducerRowStatus": "bayesfilter.runtime",
    "RegularizationConvention": "bayesfilter.inference",
    "RunManifest": "bayesfilter.runtime",
    "SpectralDerivativeCertificationResult": "bayesfilter.backends",
    "StatePartition": "bayesfilter.structural",
    "StageEvent": "bayesfilter.runtime",
    "TIMING_BUCKET_NAMES": "bayesfilter.runtime",
    "StructuralFilterConfig": "bayesfilter.structural",
    "SolveResidualError": "bayesfilter.inference",
    "StationarityError": "bayesfilter.inference",
    "TargetFailureClassification": "bayesfilter.inference",
    "TargetFailurePolicy": "bayesfilter.inference",
    "TargetPolicyEvaluation": "bayesfilter.inference",
    "TargetRegionError": "bayesfilter.inference",
    "TFFilterDerivativeResult": "bayesfilter.results_tf",
    "TFFilterDiagnostics": "bayesfilter.diagnostics",
    "TFFilterValueResult": "bayesfilter.results_tf",
    "TFLinearGaussianStateSpace": "bayesfilter.linear.types_tf",
    "TFLinearGaussianStateSpaceDerivatives": "bayesfilter.linear.types_tf",
    "TFLinearValueBackend": "bayesfilter.linear.kalman_tf",
    "TFQRLinearDerivativeBackend": "bayesfilter.linear.kalman_qr_derivatives_tf",
    "TFQRLinearValueBackend": "bayesfilter.linear.kalman_qr_tf",
    "TFSVDLinearValueBackend": "bayesfilter.linear.kalman_svd_tf",
    "TFRegularizationDiagnostics": "bayesfilter.diagnostics",
    "TFSigmaPointDiagnostics": "bayesfilter.nonlinear.sigma_points_tf",
    "TFSigmaPointRule": "bayesfilter.nonlinear.sigma_points_tf",
    "TFSigmaPointValueBackend": "bayesfilter.nonlinear.sigma_points_tf",
    "TFStructuralFirstDerivatives": (
        "bayesfilter.nonlinear.svd_sigma_point_derivatives_tf"
    ),
    "TFStructuralStateSpace": "bayesfilter.structural_tf",
    "TFSmoothEighFactorFirstDerivatives": (
        "bayesfilter.nonlinear.svd_sigma_point_derivatives_tf"
    ),
    "TimingBucket": "bayesfilter.runtime",
    "TimeoutRecord": "bayesfilter.runtime",
    "UnsupportedValueScoreAuthority": "bayesfilter.inference",
    "ValueScoreCapability": "bayesfilter.inference",
    "ValueScorePosteriorAdapter": "bayesfilter.inference",
    "WelfordCovarianceResult": "bayesfilter.inference",
    "WindowedMassAdaptationConfig": "bayesfilter.inference",
    "WindowedMassAdaptationResult": "bayesfilter.inference",
    "WindowedMassUpdate": "bayesfilter.inference",
    "WindowedWarmupWindow": "bayesfilter.inference",
    "VALID_REDUCER_STATUSES": "bayesfilter.runtime",
    "WorkerManifest": "bayesfilter.runtime",
    "WorkerRecord": "bayesfilter.runtime",
    "affine_structural_to_linear_gaussian_tf": "bayesfilter.structural_tf",
    "append_heartbeat": "bayesfilter.runtime",
    "append_stage_event": "bayesfilter.runtime",
    "assert_cpu_only_env": "bayesfilter.runtime",
    "build_trusted_gpu_snapshot": "bayesfilter.runtime",
    "build_worker_manifest": "bayesfilter.runtime",
    "canonical_candidate_order": "bayesfilter.runtime",
    "build_windowed_warmup_schedule": "bayesfilter.inference",
    "configs_match_exact": "bayesfilter.runtime",
    "classify_target_failure_mode": "bayesfilter.inference",
    "classify_fixed_kernel_screen_with_tuning_policy": "bayesfilter.inference",
    "classify_hmc_screen": "bayesfilter.inference",
    "classify_hmc_tuning_diagnostic": "bayesfilter.inference",
    "covariance_from_negative_hessian": "bayesfilter.inference",
    "covariance_from_precision": "bayesfilter.inference",
    "ensure_cpu_only_env": "bayesfilter.runtime",
    "evaluate_target_with_failure_policy": "bayesfilter.inference",
    "find_forbidden_compiled_value_tokens": "bayesfilter.nonlinear",
    "latent_to_position": "bayesfilter.inference",
    "latent_value_and_score": "bayesfilter.inference",
    "make_affine_structural_tf": "bayesfilter.structural_tf",
    "make_timing_bucket": "bayesfilter.runtime",
    "pointwise_deterministic_residuals": "bayesfilter.structural_tf",
    "production_leapfrog_count": "bayesfilter.inference",
    "record_timeout": "bayesfilter.runtime",
    "record_worker_result": "bayesfilter.runtime",
    "regularize_covariance": "bayesfilter.inference",
    "reduce_worker_artifacts": "bayesfilter.runtime",
    "normalize_hmc_tuning_policy": "bayesfilter.inference",
    "require_executable_tuning_policy": "bayesfilter.inference",
    "run_fixed_trajectory_tuning_diagnostic": "bayesfilter.inference",
    "run_gaussian_dual_averaging_diagnostic": "bayesfilter.inference",
    "run_windowed_mass_adaptation_diagnostic": "bayesfilter.inference",
    "run_full_chain_tfp_hmc": "bayesfilter.inference",
    "select_first_tie_candidate": "bayesfilter.runtime",
    "select_preferred_gpu": "bayesfilter.runtime",
    "screen_hmc_diagnostics": "bayesfilter.inference",
    "solve_kalman_score_hessian": "bayesfilter.linear.kalman_derivatives_numpy",
    "stable_adapter_signature": "bayesfilter.inference",
    "stale_artifacts_match_exact": "bayesfilter.runtime",
    "stable_config_hash": "bayesfilter.runtime",
    "stale_match_payload": "bayesfilter.runtime",
    "stable_nonlinear_filter_value_path_signature": "bayesfilter.nonlinear",
    "stable_nonlinear_ssm_program_signature": "bayesfilter.inference",
    "static_unroll_chain_value_and_score": "bayesfilter.inference",
    "structural_block_metadata": "bayesfilter.structural_tf",
    "structural_filter_diagnostics": "bayesfilter.structural_tf",
    "structural_filter_metadata": "bayesfilter.structural_tf",
    "summarize_hmc_diagnostics": "bayesfilter.inference",
    "summarize_log_accept_ratios": "bayesfilter.inference",
    "tf_cut4g_sigma_point_rule": "bayesfilter.nonlinear.cut_tf",
    "tf_kalman_filter": "bayesfilter.linear.kalman_tf",
    "tf_kalman_log_likelihood": "bayesfilter.linear.kalman_tf",
    "tf_linear_gaussian_log_likelihood": "bayesfilter.linear.kalman_tf",
    "tf_masked_kalman_filter": "bayesfilter.linear.kalman_tf",
    "tf_masked_kalman_log_likelihood": "bayesfilter.linear.kalman_tf",
    "tf_qr_linear_gaussian_log_likelihood": "bayesfilter.linear.kalman_qr_tf",
    "tf_qr_linear_gaussian_score": (
        "bayesfilter.linear.kalman_qr_derivatives_tf"
    ),
    "tf_qr_linear_gaussian_score_hessian": (
        "bayesfilter.linear.kalman_qr_derivatives_tf"
    ),
    "tf_qr_sqrt_kalman_filter": "bayesfilter.linear.kalman_qr_tf",
    "tf_qr_sqrt_kalman_log_likelihood": "bayesfilter.linear.kalman_qr_tf",
    "tf_qr_sqrt_kalman_score_hessian": (
        "bayesfilter.linear.kalman_qr_derivatives_tf"
    ),
    "tf_qr_sqrt_masked_kalman_filter": "bayesfilter.linear.kalman_qr_tf",
    "tf_qr_sqrt_masked_kalman_log_likelihood": (
        "bayesfilter.linear.kalman_qr_tf"
    ),
    "tf_qr_sqrt_masked_kalman_score_hessian": (
        "bayesfilter.linear.kalman_qr_derivatives_tf"
    ),
    "tf_svd_cubature_score": "bayesfilter.nonlinear.svd_sigma_point_derivatives_tf",
    "tf_svd_cut4_filter": "bayesfilter.nonlinear.svd_cut_tf",
    "tf_svd_cut4_log_likelihood": "bayesfilter.nonlinear.svd_cut_tf",
    "tf_svd_cut4_score": "bayesfilter.nonlinear.svd_sigma_point_derivatives_tf",
    "tf_svd_kalman_log_likelihood": "bayesfilter.linear.kalman_svd_tf",
    "tf_svd_linear_gaussian_log_likelihood": "bayesfilter.linear.kalman_svd_tf",
    "tf_svd_linear_gaussian_score_hessian": (
        "bayesfilter.linear.kalman_svd_derivatives_tf"
    ),
    "tf_svd_masked_kalman_log_likelihood": "bayesfilter.linear.kalman_svd_tf",
    "tf_svd_sigma_point_filter": "bayesfilter.nonlinear.sigma_points_tf",
    "tf_svd_sigma_point_log_likelihood": "bayesfilter.nonlinear.sigma_points_tf",
    "tf_svd_sigma_point_log_likelihood_with_rule": (
        "bayesfilter.nonlinear.sigma_points_tf"
    ),
    "tf_svd_sigma_point_placement": "bayesfilter.nonlinear.sigma_points_tf",
    "tf_svd_sigma_point_score_with_rule": (
        "bayesfilter.nonlinear.svd_sigma_point_derivatives_tf"
    ),
    "tf_svd_ukf_score": "bayesfilter.nonlinear.svd_sigma_point_derivatives_tf",
    "tensorflow_nonlinear_value_path_contract": "bayesfilter.nonlinear",
    "tf_unit_sigma_point_rule": "bayesfilter.nonlinear.sigma_points_tf",
    "validate_precomputed_map": "bayesfilter.inference",
    "validate_windowed_shrinkage_target": "bayesfilter.inference",
    "validate_nonlinear_ssm_contract": "bayesfilter.inference",
    "validate_filter_config": "bayesfilter.structural",
    "value_score_capability": "bayesfilter.inference",
    "welford_covariance": "bayesfilter.inference",
    "whitening_from_covariance": "bayesfilter.inference",
    "write_partial_result_snapshot": "bayesfilter.runtime",
    "write_evidence_manifest": "bayesfilter.runtime",
    "write_worker_manifest": "bayesfilter.runtime",
}


def __getattr__(name: str):
    try:
        module_name = _EXPORT_MODULES[name]
    except KeyError as exc:
        raise AttributeError(
            f"module {__name__!r} has no attribute {name!r}"
        ) from exc
    value = getattr(import_module(module_name), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
