"""BayesFilter core contracts and reference backends."""

from __future__ import annotations

from importlib import import_module

__all__ = [
    "CompiledValuePathClassification",
    "CompiledValuePathMode",
    "FactorBackendAuditResult",
    "BackendParityGate",
    "BackendParityResult",
    "BackendParityRow",
    "BatchValueScoreMetadata",
    "BatchValueScoreResult",
    "CovariancePositiveDefiniteError",
    "FilterDerivativeResult",
    "FilterRunMetadata",
    "FilterValueResult",
    "FixedSizeHMCChunkConfig",
    "FixedSizeHMCChunkRunResult",
    "FixedSizeHMCChunkRunner",
    "FullChainHMCConfig",
    "FullChainHMCRunResult",
    "HMCSampleArchiveManifest",
    "HMCStreamingSampleArchiveSink",
    "InternalSegmentHMCRunResult",
    "InternalSegmentHMCRunner",
    "InternalSegmentHMCRunnerConfig",
    "RetainedSampleHMCArchiveConfig",
    "RetainedSampleHMCArchiveRunResult",
    "RetainedSampleHMCArchiveRunner",
    "SEQUENTIAL_RHAT_CHECKPOINT_KINDS",
    "SEQUENTIAL_RHAT_CHECKPOINT_PUBLIC_NONCLAIMS",
    "SEQUENTIAL_RHAT_CHECKPOINT_PUBLIC_REFERENCE_FIELDS",
    "SequentialRHatCheckpointWriterConfig",
    "SequentialRHatHMCVerificationConfig",
    "SequentialRHatHMCVerificationResult",
    "SequentialRHatHMCVerifier",
    "ReusableFullChainHMCRunner",
    "BUDGET_LADDER_NONCLAIMS",
    "BOOTSTRAP_SCREEN_NONCLAIMS",
    "GEOMETRY_INITIALIZATION_NONCLAIMS",
    "FROZEN_STEP_TRAJECTORY_STAGE_NONCLAIMS",
    "GENERIC_HMC_TUNING_NONCLAIMS",
    "GenericHMCFixedGridScaleConfig",
    "GenericHMCFixedGridScaleProbe",
    "GenericHMCFixedGridScaleSelection",
    "GenericHMCCandidateEvaluation",
    "GenericHMCCandidateResult",
    "GenericHMCTuningArtifact",
    "GenericHMCTuningConfig",
    "GenericHMCTuningResult",
    "HMCGeometryInitializationConfig",
    "HMCGeometryInitializationResult",
    "HMCBootstrapRepairRound",
    "HMCBootstrapScreenConfig",
    "HMCBootstrapScreenResult",
    "HMCFixedMassStepStageConfig",
    "HMCFixedMassStepStageResult",
    "HMCFrozenStepTrajectoryStageConfig",
    "HMCFrozenStepTrajectoryStageResult",
    "HMCKernelTuningConfig",
    "HMCKernelTuningResult",
    "HMCTuneVerifyRepairAttempt",
    "HMCTuneVerifyRepairLoopConfig",
    "HMCTuneVerifyRepairLoopResult",
    "HMCWindowedMassStageConfig",
    "HMCWindowedMassStageResult",
    "HMC_KERNEL_TUNING_PUBLIC_NONCLAIMS",
    "CandidateResult",
    "EVIDENCE_MANIFEST_SCOPES",
    "EvidenceManifest",
    "GPUSelection",
    "HMCFailureClassification",
    "HMC_TUNING_POLICY_LABELS",
    "HMCDiagnosticSummary",
    "HMCLogAcceptSummary",
    "HMCScreenResult",
    "HMCTuningDiagnosticResult",
    "HMCTuningPolicy",
    "HessianPosteriorAdapter",
    "FactorizationFailure",
    "FixedTrajectoryCandidateResult",
    "FixedTrajectoryTuningConfig",
    "FixedTrajectoryTuningResult",
    "FixedMassHMCTuningBudgetCallbackResult",
    "FixedMassHMCTuningBudgetLadderConfig",
    "FixedMassHMCTuningBudgetLadderResult",
    "FixedMassHMCTuningBudgetRound",
    "FixedTransportHMCCandidateResult",
    "FixedTransportHMCJointPilotRow",
    "FixedTransportHMCJointPreparedGrid",
    "FixedTransportHMCJointPreparedGridConfig",
    "FixedTransportHMCPreparedGrid",
    "FixedTransportHMCPreparedGridConfig",
    "FixedTransportHMCGridCandidateSpec",
    "FixedTransportHMCGridPolicyConfig",
    "FixedTransportHMCGridPolicySpec",
    "FixedTransportHMCKernelTuningConfig",
    "FixedTransportHMCKernelTuningResult",
    "FIXED_TRANSPORT_HMC_ADAPTIVE_JOINT_PREPARED_GRID_NONCLAIMS",
    "FIXED_TRANSPORT_HMC_GRID_POLICY_NONCLAIMS",
    "FIXED_TRANSPORT_HMC_JOINT_PREPARED_GRID_NONCLAIMS",
    "FIXED_TRANSPORT_HMC_PREPARED_GRID_NONCLAIMS",
    "FIXED_TRANSPORT_HMC_TUNING_NONCLAIMS",
    "FixedTransportValueScoreAdapter",
    "InvalidCompiledValuePathContract",
    "InvalidNonlinearSSMContract",
    "LinearGaussianStateSpace",
    "LinearGaussianStateSpaceDerivatives",
    "LatentAffineHMCTransform",
    "MassMatrixResult",
    "NonlinearFilterValuePathContract",
    "NonlinearFilterValueStaticShape",
    "NonlinearSSMAdapterContract",
    "NonlinearSSMStaticShape",
    "ObservationSemantics",
    "ParameterTransformMetadata",
    "PosteriorAdapter",
    "PrecomputedMassArtifact",
    "PrecomputedMAP",
    "PartialResultSnapshot",
    "PriorSupportError",
    "ReducerRowStatus",
    "RegularizationConvention",
    "RetainedFrozenKernelAdapterReplayResult",
    "RunManifest",
    "SpectralDerivativeCertificationResult",
    "StatePartition",
    "StageEvent",
    "TIMING_BUCKET_NAMES",
    "TFFilterDerivativeResult",
    "TFFilterDiagnostics",
    "TFFilterValueResult",
    "TFFixedSGQF1DLevelRule",
    "TFFixedSGQFAffineModel",
    "TFFixedSGQFBranchConfig",
    "TFFixedSGQFBranchHash",
    "TFFixedSGQFBranchIdentity",
    "TFFixedSGQFBranchManifest",
    "TFFixedSGQFCloud",
    "TFFixedSGQFDerivatives",
    "TFFixedSGQFNonlinearModel",
    "TFFixedSGQFOneStepOracle",
    "TFFixedSGQFScoreResult",
    "TFFixedSGQFStepFailure",
    "TFFixedSGQFStepResult",
    "TFFixedSGQFValueResult",
    "TFLinearGaussianStateSpace",
    "TFLinearGaussianStateSpaceDerivatives",
    "TFLinearGaussianStateSpaceFirstDerivatives",
    "TFLinearValueBackend",
    "TFQRLinearDerivativeBackend",
    "TFQRLinearValueBackend",
    "SVD_LINEAR_SCORE_STATUS_BLOCKED_ACTIVE_FLOOR",
    "SVD_LINEAR_SCORE_STATUS_INVALID_EIGENSOLVER_INPUT",
    "SVD_LINEAR_SCORE_STATUS_VALID_PRE_REGULARIZED",
    "StationaryLGSSMFirstDerivativeCoverage",
    "TFSVDLinearValueBackend",
    "TFRegularizationDiagnostics",
    "TFSigmaPointDiagnostics",
    "TFSigmaPointRule",
    "TFSigmaPointValueBackend",
    "TFStructuralFirstDerivatives",
    "TFStructuralStateSpace",
    "TFSmoothEighFactorFirstDerivatives",
    "TimingBucket",
    "TimeoutRecord",
    "UnsupportedValueScoreAuthority",
    "ValueScoreCapability",
    "ValueScorePosteriorAdapter",
    "WelfordCovarianceResult",
    "WindowedMassAdaptationConfig",
    "WindowedMassAdaptationResult",
    "WindowedMassUpdate",
    "WindowedWarmupWindow",
    "WINDOWED_MASS_STAGE_NONCLAIMS",
    "FIXED_MASS_STEP_STAGE_NONCLAIMS",
    "TUNE_VERIFY_REPAIR_LOOP_NONCLAIMS",
    "VALID_REDUCER_STATUSES",
    "WorkerManifest",
    "WorkerRecord",
    "StructuralFilterConfig",
    "SolveResidualError",
    "StationarityError",
    "TargetFailureClassification",
    "TargetFailurePolicy",
    "TargetPolicyEvaluation",
    "TargetRegionError",
    "affine_structural_to_linear_gaussian_tf",
    "append_heartbeat",
    "assert_cpu_only_env",
    "append_stage_event",
    "audit_factor_backend",
    "assert_sequential_rhat_checkpoint_public_reference_safe",
    "build_trusted_gpu_snapshot",
    "build_fixed_transport_hmc_grid_policy_spec",
    "prepare_fixed_transport_hmc_adaptive_joint_grid_policy",
    "prepare_fixed_transport_hmc_grid_policy",
    "prepare_fixed_transport_hmc_joint_grid_policy",
    "build_fixed_size_hmc_chunk_runner",
    "build_internal_segment_hmc_runner",
    "build_retained_sample_hmc_archive_runner",
    "build_retained_frozen_kernel_hmc_adapter_from_tuning_payload",
    "build_reusable_full_chain_tfp_hmc_runner",
    "build_sequential_rhat_checkpoint_public_reference",
    "build_sequential_rhat_hmc_verifier",
    "build_worker_manifest",
    "canonical_candidate_order",
    "build_windowed_warmup_schedule",
    "certify_spectral_derivative_region",
    "classify_hmc_fixed_grid_acceptance",
    "classify_target_failure_mode",
    "configs_match_exact",
    "classify_fixed_kernel_screen_with_tuning_policy",
    "classify_hmc_screen",
    "classify_hmc_tuning_diagnostic",
    "covariance_from_negative_hessian",
    "covariance_from_precision",
    "continuous_lyapunov_first_derivatives_tf",
    "continuous_lyapunov_solution_tf",
    "diffusion_from_cholesky_first_derivatives_tf",
    "ensure_cpu_only_env",
    "evaluate_target_with_failure_policy",
    "evaluate_batch_native_value_score",
    "first_to_full_linear_gaussian_derivatives",
    "find_forbidden_compiled_value_tokens",
    "initialize_hmc_kernel_geometry",
    "inspect_sequential_rhat_private_checkpoint",
    "latent_to_position",
    "latent_value_and_score",
    "make_affine_structural_tf",
    "matrix_exponential_frechet_tf",
    "make_timing_bucket",
    "pointwise_deterministic_residuals",
    "production_leapfrog_count",
    "record_timeout",
    "record_worker_result",
    "regularize_covariance",
    "reduce_worker_artifacts",
    "normalize_hmc_tuning_policy",
    "orchestrate_generic_hmc_tuning",
    "require_executable_tuning_policy",
    "run_fixed_trajectory_tuning_diagnostic",
    "run_fixed_mass_hmc_tuning_budget_ladder",
    "run_generic_hmc_tuning_orchestration",
    "run_gaussian_dual_averaging_diagnostic",
    "run_windowed_mass_adaptation_diagnostic",
    "run_full_chain_tfp_hmc",
    "run_hmc_bootstrap_screen",
    "run_hmc_fixed_mass_step_stage",
    "run_hmc_frozen_step_trajectory_stage",
    "run_hmc_tune_verify_repair_loop",
    "run_hmc_windowed_mass_stage",
    "tune_hmc_kernel",
    "tune_fixed_transport_hmc_kernel",
    "reviewed_value_score_target_fn",
    "select_hmc_fixed_grid_scale",
    "select_first_tie_candidate",
    "select_preferred_gpu",
    "screen_hmc_diagnostics",
    "sequential_rhat_verification_checkpoint_contract",
    "solve_kalman_score_hessian",
    "stable_adapter_signature",
    "stationary_lgssm_first_derivative_coverage",
    "stationary_lgssm_from_continuous_first_derivatives_tf",
    "stale_artifacts_match_exact",
    "stable_config_hash",
    "stale_match_payload",
    "stable_nonlinear_filter_value_path_signature",
    "stable_nonlinear_ssm_program_signature",
    "static_unroll_chain_value_and_score",
    "structural_block_metadata",
    "structural_filter_diagnostics",
    "structural_filter_metadata",
    "summarize_hmc_diagnostics",
    "summarize_log_accept_ratios",
    "tf_cut4g_sigma_point_rule",
    "tf_fixed_sgqf_active_multi_indices",
    "tf_fixed_sgqf_branch_identity",
    "tf_fixed_sgqf_cloud",
    "tf_fixed_sgqf_combination_coefficient",
    "tf_fixed_sgqf_filter",
    "tf_fixed_sgqf_p47_one_step_oracle",
    "tf_fixed_sgqf_same_branch_signature",
    "tf_fixed_sgqf_score",
    "tf_kalman_filter",
    "tf_kalman_log_likelihood",
    "tf_linear_gaussian_log_likelihood",
    "tf_masked_kalman_filter",
    "tf_masked_kalman_log_likelihood",
    "tf_qr_linear_gaussian_log_likelihood",
    "tf_qr_linear_gaussian_score",
    "tf_qr_linear_gaussian_score_hessian",
    "tf_qr_sqrt_kalman_filter",
    "tf_qr_sqrt_kalman_log_likelihood",
    "tf_qr_sqrt_kalman_score_hessian",
    "tf_qr_sqrt_masked_kalman_filter",
    "tf_qr_sqrt_masked_kalman_log_likelihood",
    "tf_qr_sqrt_masked_kalman_score_hessian",
    "tf_svd_cubature_score",
    "tf_svd_cut4_filter",
    "tf_svd_cut4_log_likelihood",
    "tf_svd_cut4_score",
    "tf_svd_kalman_log_likelihood",
    "tf_svd_linear_gaussian_log_likelihood",
    "tf_svd_linear_gaussian_score_first_order",
    "tf_svd_linear_gaussian_score_first_order_graph_status",
    "tf_svd_linear_gaussian_score_hessian",
    "tf_svd_linear_gaussian_score_hessian_graph_status",
    "tf_svd_masked_kalman_log_likelihood",
    "tf_batched_svd_sigma_point_value_and_score_custom_gradient",
    "tf_svd_sigma_point_filter",
    "tf_svd_sigma_point_log_likelihood",
    "tf_svd_sigma_point_log_likelihood_with_rule",
    "tf_svd_sigma_point_placement",
    "tf_svd_sigma_point_score_with_rule",
    "tf_svd_ukf_score",
    "tf_standard_normal_ghq_level_rule",
    "tensorflow_nonlinear_value_path_contract",
    "tf_unit_sigma_point_rule",
    "validate_precomputed_map",
    "validate_windowed_shrinkage_target",
    "validate_filter_config",
    "validate_nonlinear_ssm_contract",
    "value_score_capability",
    "welford_covariance",
    "whitening_from_covariance",
    "write_partial_result_snapshot",
    "write_evidence_manifest",
    "write_hmc_sample_archive",
    "write_sequential_rhat_boundary_handoff_checkpoint",
    "write_sequential_rhat_pre_verification_handoff_checkpoint",
    "write_worker_manifest",
]

_EXPORT_MODULES = {
    "CompiledValuePathClassification": "bayesfilter.nonlinear",
    "CompiledValuePathMode": "bayesfilter.nonlinear",
    "FactorBackendAuditResult": "bayesfilter.backends",
    "BackendParityGate": "bayesfilter.inference",
    "BackendParityResult": "bayesfilter.inference",
    "BackendParityRow": "bayesfilter.inference",
    "BatchValueScoreMetadata": "bayesfilter.inference",
    "BatchValueScoreResult": "bayesfilter.inference",
    "CovariancePositiveDefiniteError": "bayesfilter.inference",
    "SpectralDerivativeCertificationResult": "bayesfilter.backends",
    "audit_factor_backend": "bayesfilter.backends",
    "certify_spectral_derivative_region": "bayesfilter.backends",
    "FilterDerivativeResult": "bayesfilter.results",
    "FilterRunMetadata": "bayesfilter.structural",
    "FilterValueResult": "bayesfilter.results",
    "FixedSizeHMCChunkConfig": "bayesfilter.inference",
    "FixedSizeHMCChunkRunResult": "bayesfilter.inference",
    "FixedSizeHMCChunkRunner": "bayesfilter.inference",
    "FullChainHMCConfig": "bayesfilter.inference",
    "FullChainHMCRunResult": "bayesfilter.inference",
    "HMCSampleArchiveManifest": "bayesfilter.inference",
    "HMCStreamingSampleArchiveSink": "bayesfilter.inference",
    "InternalSegmentHMCRunResult": "bayesfilter.inference",
    "InternalSegmentHMCRunner": "bayesfilter.inference",
    "InternalSegmentHMCRunnerConfig": "bayesfilter.inference",
    "RetainedSampleHMCArchiveConfig": "bayesfilter.inference",
    "RetainedSampleHMCArchiveRunResult": "bayesfilter.inference",
    "RetainedSampleHMCArchiveRunner": "bayesfilter.inference",
    "SEQUENTIAL_RHAT_CHECKPOINT_KINDS": "bayesfilter.inference",
    "SEQUENTIAL_RHAT_CHECKPOINT_PUBLIC_NONCLAIMS": "bayesfilter.inference",
    "SEQUENTIAL_RHAT_CHECKPOINT_PUBLIC_REFERENCE_FIELDS": "bayesfilter.inference",
    "SequentialRHatCheckpointWriterConfig": "bayesfilter.inference",
    "SequentialRHatHMCVerificationConfig": "bayesfilter.inference",
    "SequentialRHatHMCVerificationResult": "bayesfilter.inference",
    "SequentialRHatHMCVerifier": "bayesfilter.inference",
    "ReusableFullChainHMCRunner": "bayesfilter.inference",
    "BUDGET_LADDER_NONCLAIMS": "bayesfilter.inference",
    "BOOTSTRAP_SCREEN_NONCLAIMS": "bayesfilter.inference",
    "GEOMETRY_INITIALIZATION_NONCLAIMS": "bayesfilter.inference",
    "FROZEN_STEP_TRAJECTORY_STAGE_NONCLAIMS": "bayesfilter.inference",
    "GENERIC_HMC_TUNING_NONCLAIMS": "bayesfilter.inference",
    "GenericHMCFixedGridScaleConfig": "bayesfilter.inference",
    "GenericHMCFixedGridScaleProbe": "bayesfilter.inference",
    "GenericHMCFixedGridScaleSelection": "bayesfilter.inference",
    "GenericHMCCandidateEvaluation": "bayesfilter.inference",
    "GenericHMCCandidateResult": "bayesfilter.inference",
    "GenericHMCTuningArtifact": "bayesfilter.inference",
    "GenericHMCTuningConfig": "bayesfilter.inference",
    "GenericHMCTuningResult": "bayesfilter.inference",
    "HMCGeometryInitializationConfig": "bayesfilter.inference",
    "HMCGeometryInitializationResult": "bayesfilter.inference",
    "HMCBootstrapRepairRound": "bayesfilter.inference",
    "HMCBootstrapScreenConfig": "bayesfilter.inference",
    "HMCBootstrapScreenResult": "bayesfilter.inference",
    "HMCFixedMassStepStageConfig": "bayesfilter.inference",
    "HMCFixedMassStepStageResult": "bayesfilter.inference",
    "HMCFrozenStepTrajectoryStageConfig": "bayesfilter.inference",
    "HMCFrozenStepTrajectoryStageResult": "bayesfilter.inference",
    "HMCKernelTuningConfig": "bayesfilter.inference",
    "HMCKernelTuningResult": "bayesfilter.inference",
    "HMCTuneVerifyRepairAttempt": "bayesfilter.inference",
    "HMCTuneVerifyRepairLoopConfig": "bayesfilter.inference",
    "HMCTuneVerifyRepairLoopResult": "bayesfilter.inference",
    "HMCWindowedMassStageConfig": "bayesfilter.inference",
    "HMCWindowedMassStageResult": "bayesfilter.inference",
    "HMC_KERNEL_TUNING_PUBLIC_NONCLAIMS": "bayesfilter.inference",
    "CandidateResult": "bayesfilter.runtime",
    "EVIDENCE_MANIFEST_SCOPES": "bayesfilter.runtime",
    "EvidenceManifest": "bayesfilter.runtime",
    "GPUSelection": "bayesfilter.runtime",
    "HMCFailureClassification": "bayesfilter.inference",
    "HMC_TUNING_POLICY_LABELS": "bayesfilter.inference",
    "HMCDiagnosticSummary": "bayesfilter.inference",
    "HMCLogAcceptSummary": "bayesfilter.inference",
    "HMCScreenResult": "bayesfilter.inference",
    "HMCTuningDiagnosticResult": "bayesfilter.inference",
    "HMCTuningPolicy": "bayesfilter.inference",
    "HessianPosteriorAdapter": "bayesfilter.inference",
    "FactorizationFailure": "bayesfilter.inference",
    "FixedTrajectoryCandidateResult": "bayesfilter.inference",
    "FixedTrajectoryTuningConfig": "bayesfilter.inference",
    "FixedTrajectoryTuningResult": "bayesfilter.inference",
    "FixedMassHMCTuningBudgetCallbackResult": "bayesfilter.inference",
    "FixedMassHMCTuningBudgetLadderConfig": "bayesfilter.inference",
    "FixedMassHMCTuningBudgetLadderResult": "bayesfilter.inference",
    "FixedMassHMCTuningBudgetRound": "bayesfilter.inference",
    "FixedTransportHMCCandidateResult": "bayesfilter.inference",
    "FixedTransportHMCJointPilotRow": "bayesfilter.inference",
    "FixedTransportHMCJointPreparedGrid": "bayesfilter.inference",
    "FixedTransportHMCJointPreparedGridConfig": "bayesfilter.inference",
    "FixedTransportHMCPreparedGrid": "bayesfilter.inference",
    "FixedTransportHMCPreparedGridConfig": "bayesfilter.inference",
    "FixedTransportHMCGridCandidateSpec": "bayesfilter.inference",
    "FixedTransportHMCGridPolicyConfig": "bayesfilter.inference",
    "FixedTransportHMCGridPolicySpec": "bayesfilter.inference",
    "FixedTransportHMCKernelTuningConfig": "bayesfilter.inference",
    "FixedTransportHMCKernelTuningResult": "bayesfilter.inference",
    "FIXED_TRANSPORT_HMC_ADAPTIVE_JOINT_PREPARED_GRID_NONCLAIMS": "bayesfilter.inference",
    "FIXED_TRANSPORT_HMC_GRID_POLICY_NONCLAIMS": "bayesfilter.inference",
    "FIXED_TRANSPORT_HMC_JOINT_PREPARED_GRID_NONCLAIMS": "bayesfilter.inference",
    "FIXED_TRANSPORT_HMC_PREPARED_GRID_NONCLAIMS": "bayesfilter.inference",
    "FIXED_TRANSPORT_HMC_TUNING_NONCLAIMS": "bayesfilter.inference",
    "FixedTransportValueScoreAdapter": "bayesfilter.inference",
    "InvalidCompiledValuePathContract": "bayesfilter.nonlinear",
    "InvalidNonlinearSSMContract": "bayesfilter.inference",
    "LinearGaussianStateSpace": "bayesfilter.linear.types",
    "LinearGaussianStateSpaceDerivatives": "bayesfilter.linear.types",
    "LatentAffineHMCTransform": "bayesfilter.inference",
    "MassMatrixResult": "bayesfilter.inference",
    "NonlinearFilterValuePathContract": "bayesfilter.nonlinear",
    "NonlinearFilterValueStaticShape": "bayesfilter.nonlinear",
    "NonlinearSSMAdapterContract": "bayesfilter.inference",
    "NonlinearSSMStaticShape": "bayesfilter.inference",
    "ObservationSemantics": "bayesfilter.inference",
    "ParameterTransformMetadata": "bayesfilter.inference",
    "PosteriorAdapter": "bayesfilter.inference",
    "PrecomputedMassArtifact": "bayesfilter.inference",
    "PrecomputedMAP": "bayesfilter.inference",
    "PriorSupportError": "bayesfilter.inference",
    "PartialResultSnapshot": "bayesfilter.runtime",
    "ReducerRowStatus": "bayesfilter.runtime",
    "RegularizationConvention": "bayesfilter.inference",
    "RetainedFrozenKernelAdapterReplayResult": "bayesfilter.inference",
    "RunManifest": "bayesfilter.runtime",
    "SpectralDerivativeCertificationResult": "bayesfilter.backends",
    "StatePartition": "bayesfilter.structural",
    "StageEvent": "bayesfilter.runtime",
    "TIMING_BUCKET_NAMES": "bayesfilter.runtime",
    "StructuralFilterConfig": "bayesfilter.structural",
    "SolveResidualError": "bayesfilter.inference",
    "StationarityError": "bayesfilter.inference",
    "TargetFailureClassification": "bayesfilter.inference",
    "TargetFailurePolicy": "bayesfilter.inference",
    "TargetPolicyEvaluation": "bayesfilter.inference",
    "TargetRegionError": "bayesfilter.inference",
    "TFFilterDerivativeResult": "bayesfilter.results_tf",
    "TFFilterDiagnostics": "bayesfilter.diagnostics",
    "TFFilterValueResult": "bayesfilter.results_tf",
    "TFFixedSGQF1DLevelRule": "bayesfilter.nonlinear",
    "TFFixedSGQFAffineModel": "bayesfilter.nonlinear",
    "TFFixedSGQFBranchConfig": "bayesfilter.nonlinear",
    "TFFixedSGQFBranchHash": "bayesfilter.nonlinear",
    "TFFixedSGQFBranchIdentity": "bayesfilter.nonlinear",
    "TFFixedSGQFBranchManifest": "bayesfilter.nonlinear",
    "TFFixedSGQFCloud": "bayesfilter.nonlinear",
    "TFFixedSGQFDerivatives": "bayesfilter.nonlinear",
    "TFFixedSGQFNonlinearModel": "bayesfilter.nonlinear",
    "TFFixedSGQFOneStepOracle": "bayesfilter.nonlinear",
    "TFFixedSGQFScoreResult": "bayesfilter.nonlinear",
    "TFFixedSGQFStepFailure": "bayesfilter.nonlinear",
    "TFFixedSGQFStepResult": "bayesfilter.nonlinear",
    "TFFixedSGQFValueResult": "bayesfilter.nonlinear",
    "TFLinearGaussianStateSpace": "bayesfilter.linear.types_tf",
    "TFLinearGaussianStateSpaceDerivatives": "bayesfilter.linear.types_tf",
    "TFLinearGaussianStateSpaceFirstDerivatives": "bayesfilter.linear.types_tf",
    "TFLinearValueBackend": "bayesfilter.linear.kalman_tf",
    "TFQRLinearDerivativeBackend": "bayesfilter.linear.kalman_qr_derivatives_tf",
    "TFQRLinearValueBackend": "bayesfilter.linear.kalman_qr_tf",
    "SVD_LINEAR_SCORE_STATUS_BLOCKED_ACTIVE_FLOOR": (
        "bayesfilter.linear.kalman_svd_derivatives_tf"
    ),
    "SVD_LINEAR_SCORE_STATUS_INVALID_EIGENSOLVER_INPUT": (
        "bayesfilter.linear.kalman_svd_derivatives_tf"
    ),
    "SVD_LINEAR_SCORE_STATUS_VALID_PRE_REGULARIZED": (
        "bayesfilter.linear.kalman_svd_derivatives_tf"
    ),
    "StationaryLGSSMFirstDerivativeCoverage": (
        "bayesfilter.linear.stationary_lgssm_derivatives_tf"
    ),
    "TFSVDLinearValueBackend": "bayesfilter.linear.kalman_svd_tf",
    "TFRegularizationDiagnostics": "bayesfilter.diagnostics",
    "TFSigmaPointDiagnostics": "bayesfilter.nonlinear.sigma_points_tf",
    "TFSigmaPointRule": "bayesfilter.nonlinear.sigma_points_tf",
    "TFSigmaPointValueBackend": "bayesfilter.nonlinear.sigma_points_tf",
    "TFStructuralFirstDerivatives": (
        "bayesfilter.nonlinear.svd_sigma_point_derivatives_tf"
    ),
    "TFStructuralStateSpace": "bayesfilter.structural_tf",
    "TFSmoothEighFactorFirstDerivatives": (
        "bayesfilter.nonlinear.svd_sigma_point_derivatives_tf"
    ),
    "TimingBucket": "bayesfilter.runtime",
    "TimeoutRecord": "bayesfilter.runtime",
    "UnsupportedValueScoreAuthority": "bayesfilter.inference",
    "ValueScoreCapability": "bayesfilter.inference",
    "ValueScorePosteriorAdapter": "bayesfilter.inference",
    "WelfordCovarianceResult": "bayesfilter.inference",
    "WindowedMassAdaptationConfig": "bayesfilter.inference",
    "WindowedMassAdaptationResult": "bayesfilter.inference",
    "WindowedMassUpdate": "bayesfilter.inference",
    "WindowedWarmupWindow": "bayesfilter.inference",
    "WINDOWED_MASS_STAGE_NONCLAIMS": "bayesfilter.inference",
    "FIXED_MASS_STEP_STAGE_NONCLAIMS": "bayesfilter.inference",
    "TUNE_VERIFY_REPAIR_LOOP_NONCLAIMS": "bayesfilter.inference",
    "VALID_REDUCER_STATUSES": "bayesfilter.runtime",
    "WorkerManifest": "bayesfilter.runtime",
    "WorkerRecord": "bayesfilter.runtime",
    "affine_structural_to_linear_gaussian_tf": "bayesfilter.structural_tf",
    "append_heartbeat": "bayesfilter.runtime",
    "append_stage_event": "bayesfilter.runtime",
    "assert_cpu_only_env": "bayesfilter.runtime",
    "assert_sequential_rhat_checkpoint_public_reference_safe": "bayesfilter.inference",
    "build_trusted_gpu_snapshot": "bayesfilter.runtime",
    "build_fixed_transport_hmc_grid_policy_spec": "bayesfilter.inference",
    "prepare_fixed_transport_hmc_adaptive_joint_grid_policy": "bayesfilter.inference",
    "prepare_fixed_transport_hmc_grid_policy": "bayesfilter.inference",
    "prepare_fixed_transport_hmc_joint_grid_policy": "bayesfilter.inference",
    "build_fixed_size_hmc_chunk_runner": "bayesfilter.inference",
    "build_internal_segment_hmc_runner": "bayesfilter.inference",
    "build_retained_sample_hmc_archive_runner": "bayesfilter.inference",
    "build_reusable_full_chain_tfp_hmc_runner": "bayesfilter.inference",
    "build_sequential_rhat_checkpoint_public_reference": "bayesfilter.inference",
    "build_sequential_rhat_hmc_verifier": "bayesfilter.inference",
    "build_worker_manifest": "bayesfilter.runtime",
    "canonical_candidate_order": "bayesfilter.runtime",
    "build_windowed_warmup_schedule": "bayesfilter.inference",
    "configs_match_exact": "bayesfilter.runtime",
    "classify_hmc_fixed_grid_acceptance": "bayesfilter.inference",
    "classify_target_failure_mode": "bayesfilter.inference",
    "classify_fixed_kernel_screen_with_tuning_policy": "bayesfilter.inference",
    "classify_hmc_screen": "bayesfilter.inference",
    "classify_hmc_tuning_diagnostic": "bayesfilter.inference",
    "covariance_from_negative_hessian": "bayesfilter.inference",
    "covariance_from_precision": "bayesfilter.inference",
    "continuous_lyapunov_first_derivatives_tf": (
        "bayesfilter.linear.stationary_lgssm_derivatives_tf"
    ),
    "continuous_lyapunov_solution_tf": (
        "bayesfilter.linear.stationary_lgssm_derivatives_tf"
    ),
    "diffusion_from_cholesky_first_derivatives_tf": (
        "bayesfilter.linear.stationary_lgssm_derivatives_tf"
    ),
    "ensure_cpu_only_env": "bayesfilter.runtime",
    "evaluate_target_with_failure_policy": "bayesfilter.inference",
    "evaluate_batch_native_value_score": "bayesfilter.inference",
    "first_to_full_linear_gaussian_derivatives": "bayesfilter.linear.types_tf",
    "find_forbidden_compiled_value_tokens": "bayesfilter.nonlinear",
    "initialize_hmc_kernel_geometry": "bayesfilter.inference",
    "latent_to_position": "bayesfilter.inference",
    "latent_value_and_score": "bayesfilter.inference",
    "make_affine_structural_tf": "bayesfilter.structural_tf",
    "matrix_exponential_frechet_tf": (
        "bayesfilter.linear.stationary_lgssm_derivatives_tf"
    ),
    "make_timing_bucket": "bayesfilter.runtime",
    "pointwise_deterministic_residuals": "bayesfilter.structural_tf",
    "production_leapfrog_count": "bayesfilter.inference",
    "record_timeout": "bayesfilter.runtime",
    "record_worker_result": "bayesfilter.runtime",
    "regularize_covariance": "bayesfilter.inference",
    "reduce_worker_artifacts": "bayesfilter.runtime",
    "normalize_hmc_tuning_policy": "bayesfilter.inference",
    "orchestrate_generic_hmc_tuning": "bayesfilter.inference",
    "require_executable_tuning_policy": "bayesfilter.inference",
    "run_fixed_trajectory_tuning_diagnostic": "bayesfilter.inference",
    "run_fixed_mass_hmc_tuning_budget_ladder": "bayesfilter.inference",
    "run_generic_hmc_tuning_orchestration": "bayesfilter.inference",
    "run_gaussian_dual_averaging_diagnostic": "bayesfilter.inference",
    "run_windowed_mass_adaptation_diagnostic": "bayesfilter.inference",
    "run_full_chain_tfp_hmc": "bayesfilter.inference",
    "build_retained_frozen_kernel_hmc_adapter_from_tuning_payload": "bayesfilter.inference",
    "run_hmc_bootstrap_screen": "bayesfilter.inference",
    "run_hmc_fixed_mass_step_stage": "bayesfilter.inference",
    "run_hmc_frozen_step_trajectory_stage": "bayesfilter.inference",
    "run_hmc_tune_verify_repair_loop": "bayesfilter.inference",
    "run_hmc_windowed_mass_stage": "bayesfilter.inference",
    "select_hmc_fixed_grid_scale": "bayesfilter.inference",
    "tune_hmc_kernel": "bayesfilter.inference",
    "tune_fixed_transport_hmc_kernel": "bayesfilter.inference",
    "reviewed_value_score_target_fn": "bayesfilter.inference",
    "select_first_tie_candidate": "bayesfilter.runtime",
    "select_preferred_gpu": "bayesfilter.runtime",
    "screen_hmc_diagnostics": "bayesfilter.inference",
    "sequential_rhat_verification_checkpoint_contract": "bayesfilter.inference",
    "inspect_sequential_rhat_private_checkpoint": "bayesfilter.inference",
    "solve_kalman_score_hessian": "bayesfilter.linear.kalman_derivatives_numpy",
    "stable_adapter_signature": "bayesfilter.inference",
    "stationary_lgssm_first_derivative_coverage": (
        "bayesfilter.linear.stationary_lgssm_derivatives_tf"
    ),
    "stationary_lgssm_from_continuous_first_derivatives_tf": (
        "bayesfilter.linear.stationary_lgssm_derivatives_tf"
    ),
    "stale_artifacts_match_exact": "bayesfilter.runtime",
    "stable_config_hash": "bayesfilter.runtime",
    "stale_match_payload": "bayesfilter.runtime",
    "stable_nonlinear_filter_value_path_signature": "bayesfilter.nonlinear",
    "stable_nonlinear_ssm_program_signature": "bayesfilter.inference",
    "static_unroll_chain_value_and_score": "bayesfilter.inference",
    "structural_block_metadata": "bayesfilter.structural_tf",
    "structural_filter_diagnostics": "bayesfilter.structural_tf",
    "structural_filter_metadata": "bayesfilter.structural_tf",
    "summarize_hmc_diagnostics": "bayesfilter.inference",
    "summarize_log_accept_ratios": "bayesfilter.inference",
    "tf_cut4g_sigma_point_rule": "bayesfilter.nonlinear.cut_tf",
    "tf_fixed_sgqf_active_multi_indices": "bayesfilter.nonlinear",
    "tf_fixed_sgqf_branch_identity": "bayesfilter.nonlinear",
    "tf_fixed_sgqf_cloud": "bayesfilter.nonlinear",
    "tf_fixed_sgqf_combination_coefficient": "bayesfilter.nonlinear",
    "tf_fixed_sgqf_filter": "bayesfilter.nonlinear",
    "tf_fixed_sgqf_p47_one_step_oracle": "bayesfilter.nonlinear",
    "tf_fixed_sgqf_same_branch_signature": "bayesfilter.nonlinear",
    "tf_fixed_sgqf_score": "bayesfilter.nonlinear",
    "tf_kalman_filter": "bayesfilter.linear.kalman_tf",
    "tf_kalman_log_likelihood": "bayesfilter.linear.kalman_tf",
    "tf_linear_gaussian_log_likelihood": "bayesfilter.linear.kalman_tf",
    "tf_masked_kalman_filter": "bayesfilter.linear.kalman_tf",
    "tf_masked_kalman_log_likelihood": "bayesfilter.linear.kalman_tf",
    "tf_qr_linear_gaussian_log_likelihood": "bayesfilter.linear.kalman_qr_tf",
    "tf_qr_linear_gaussian_score": (
        "bayesfilter.linear.kalman_qr_derivatives_tf"
    ),
    "tf_qr_linear_gaussian_score_hessian": (
        "bayesfilter.linear.kalman_qr_derivatives_tf"
    ),
    "tf_qr_sqrt_kalman_filter": "bayesfilter.linear.kalman_qr_tf",
    "tf_qr_sqrt_kalman_log_likelihood": "bayesfilter.linear.kalman_qr_tf",
    "tf_qr_sqrt_kalman_score_hessian": (
        "bayesfilter.linear.kalman_qr_derivatives_tf"
    ),
    "tf_qr_sqrt_masked_kalman_filter": "bayesfilter.linear.kalman_qr_tf",
    "tf_qr_sqrt_masked_kalman_log_likelihood": (
        "bayesfilter.linear.kalman_qr_tf"
    ),
    "tf_qr_sqrt_masked_kalman_score_hessian": (
        "bayesfilter.linear.kalman_qr_derivatives_tf"
    ),
    "tf_svd_cubature_score": "bayesfilter.nonlinear.svd_sigma_point_derivatives_tf",
    "tf_svd_cut4_filter": "bayesfilter.nonlinear.svd_cut_tf",
    "tf_svd_cut4_log_likelihood": "bayesfilter.nonlinear.svd_cut_tf",
    "tf_svd_cut4_score": "bayesfilter.nonlinear.svd_sigma_point_derivatives_tf",
    "tf_svd_kalman_log_likelihood": "bayesfilter.linear.kalman_svd_tf",
    "tf_svd_linear_gaussian_log_likelihood": "bayesfilter.linear.kalman_svd_tf",
    "tf_svd_linear_gaussian_score_first_order": (
        "bayesfilter.linear.kalman_svd_derivatives_tf"
    ),
    "tf_svd_linear_gaussian_score_first_order_graph_status": (
        "bayesfilter.linear.kalman_svd_derivatives_tf"
    ),
    "tf_svd_linear_gaussian_score_hessian": (
        "bayesfilter.linear.kalman_svd_derivatives_tf"
    ),
    "tf_svd_linear_gaussian_score_hessian_graph_status": (
        "bayesfilter.linear.kalman_svd_derivatives_tf"
    ),
    "tf_svd_masked_kalman_log_likelihood": "bayesfilter.linear.kalman_svd_tf",
    "tf_batched_svd_sigma_point_value_and_score_custom_gradient": (
        "bayesfilter.nonlinear.batched_svd_sigma_point_tf"
    ),
    "tf_svd_sigma_point_filter": "bayesfilter.nonlinear.sigma_points_tf",
    "tf_svd_sigma_point_log_likelihood": "bayesfilter.nonlinear.sigma_points_tf",
    "tf_svd_sigma_point_log_likelihood_with_rule": (
        "bayesfilter.nonlinear.sigma_points_tf"
    ),
    "tf_svd_sigma_point_placement": "bayesfilter.nonlinear.sigma_points_tf",
    "tf_svd_sigma_point_score_with_rule": (
        "bayesfilter.nonlinear.svd_sigma_point_derivatives_tf"
    ),
    "tf_svd_ukf_score": "bayesfilter.nonlinear.svd_sigma_point_derivatives_tf",
    "tf_standard_normal_ghq_level_rule": "bayesfilter.nonlinear",
    "tensorflow_nonlinear_value_path_contract": "bayesfilter.nonlinear",
    "tf_unit_sigma_point_rule": "bayesfilter.nonlinear.sigma_points_tf",
    "validate_precomputed_map": "bayesfilter.inference",
    "validate_windowed_shrinkage_target": "bayesfilter.inference",
    "validate_nonlinear_ssm_contract": "bayesfilter.inference",
    "validate_filter_config": "bayesfilter.structural",
    "value_score_capability": "bayesfilter.inference",
    "welford_covariance": "bayesfilter.inference",
    "whitening_from_covariance": "bayesfilter.inference",
    "write_partial_result_snapshot": "bayesfilter.runtime",
    "write_evidence_manifest": "bayesfilter.runtime",
    "write_hmc_sample_archive": "bayesfilter.inference",
    "write_sequential_rhat_boundary_handoff_checkpoint": "bayesfilter.inference",
    "write_sequential_rhat_pre_verification_handoff_checkpoint": "bayesfilter.inference",
    "write_worker_manifest": "bayesfilter.runtime",
}


def __getattr__(name: str):
    try:
        module_name = _EXPORT_MODULES[name]
    except KeyError as exc:
        raise AttributeError(
            f"module {__name__!r} has no attribute {name!r}"
        ) from exc
    value = getattr(import_module(module_name), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
